# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eegTest.ui'
#
# Created: Wed Apr 10 14:49:29 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.setEnabled(True)
        mainWindow.resize(1259, 600)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.datarate = QtGui.QTextEdit(self.centralwidget)
        self.datarate.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.datarate.setReadOnly(True)
        self.datarate.setObjectName(_fromUtf8("datarate"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.samplesperchannel = QtGui.QTextEdit(self.centralwidget)
        self.samplesperchannel.setGeometry(QtCore.QRect(10, 110, 91, 31))
        self.samplesperchannel.setObjectName(_fromUtf8("samplesperchannel"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(120, 20, 1111, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.channelregistersetting = QtGui.QWidget()
        self.channelregistersetting.setObjectName(_fromUtf8("channelregistersetting"))
        self.frameCh6 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh6.setGeometry(QtCore.QRect(570, 120, 511, 51))
        self.frameCh6.setFrameShape(QtGui.QFrame.Box)
        self.frameCh6.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh6.setObjectName(_fromUtf8("frameCh6"))
        self.PDCh6 = QtGui.QComboBox(self.frameCh6)
        self.PDCh6.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh6.setObjectName(_fromUtf8("PDCh6"))
        self.GainCh6 = QtGui.QComboBox(self.frameCh6)
        self.GainCh6.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh6.setObjectName(_fromUtf8("GainCh6"))
        self.SRB2Ch6 = QtGui.QComboBox(self.frameCh6)
        self.SRB2Ch6.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch6.setObjectName(_fromUtf8("SRB2Ch6"))
        self.ChanInCh6 = QtGui.QComboBox(self.frameCh6)
        self.ChanInCh6.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh6.setObjectName(_fromUtf8("ChanInCh6"))
        self.label_23 = QtGui.QLabel(self.frameCh6)
        self.label_23.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.frameCh6)
        self.label_24.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.frameCh6)
        self.label_25.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.frameCh6)
        self.label_26.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.frameCh7 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh7.setGeometry(QtCore.QRect(570, 190, 511, 51))
        self.frameCh7.setFrameShape(QtGui.QFrame.Box)
        self.frameCh7.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh7.setObjectName(_fromUtf8("frameCh7"))
        self.PDCh7 = QtGui.QComboBox(self.frameCh7)
        self.PDCh7.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh7.setObjectName(_fromUtf8("PDCh7"))
        self.GainCh7 = QtGui.QComboBox(self.frameCh7)
        self.GainCh7.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh7.setObjectName(_fromUtf8("GainCh7"))
        self.SRB2Ch7 = QtGui.QComboBox(self.frameCh7)
        self.SRB2Ch7.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch7.setObjectName(_fromUtf8("SRB2Ch7"))
        self.ChanInCh7 = QtGui.QComboBox(self.frameCh7)
        self.ChanInCh7.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh7.setObjectName(_fromUtf8("ChanInCh7"))
        self.label_27 = QtGui.QLabel(self.frameCh7)
        self.label_27.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.frameCh7)
        self.label_28.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.frameCh7)
        self.label_29.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.frameCh7)
        self.label_30.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.frameCh8 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh8.setGeometry(QtCore.QRect(570, 260, 511, 51))
        self.frameCh8.setFrameShape(QtGui.QFrame.Box)
        self.frameCh8.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh8.setObjectName(_fromUtf8("frameCh8"))
        self.PDCh8 = QtGui.QComboBox(self.frameCh8)
        self.PDCh8.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh8.setObjectName(_fromUtf8("PDCh8"))
        self.GainCh8 = QtGui.QComboBox(self.frameCh8)
        self.GainCh8.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh8.setObjectName(_fromUtf8("GainCh8"))
        self.SRB2Ch8 = QtGui.QComboBox(self.frameCh8)
        self.SRB2Ch8.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch8.setObjectName(_fromUtf8("SRB2Ch8"))
        self.ChanInCh8 = QtGui.QComboBox(self.frameCh8)
        self.ChanInCh8.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh8.setObjectName(_fromUtf8("ChanInCh8"))
        self.label_31 = QtGui.QLabel(self.frameCh8)
        self.label_31.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.frameCh8)
        self.label_32.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.frameCh8)
        self.label_33.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.frameCh8)
        self.label_34.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.frameCh5 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh5.setGeometry(QtCore.QRect(570, 50, 511, 51))
        self.frameCh5.setFrameShape(QtGui.QFrame.Box)
        self.frameCh5.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh5.setObjectName(_fromUtf8("frameCh5"))
        self.PDCh5 = QtGui.QComboBox(self.frameCh5)
        self.PDCh5.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh5.setObjectName(_fromUtf8("PDCh5"))
        self.GainCh5 = QtGui.QComboBox(self.frameCh5)
        self.GainCh5.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh5.setObjectName(_fromUtf8("GainCh5"))
        self.SRB2Ch5 = QtGui.QComboBox(self.frameCh5)
        self.SRB2Ch5.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch5.setObjectName(_fromUtf8("SRB2Ch5"))
        self.ChanInCh5 = QtGui.QComboBox(self.frameCh5)
        self.ChanInCh5.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh5.setObjectName(_fromUtf8("ChanInCh5"))
        self.label_35 = QtGui.QLabel(self.frameCh5)
        self.label_35.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.frameCh5)
        self.label_36.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.frameCh5)
        self.label_37.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.frameCh5)
        self.label_38.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.channelregistersetting)
        self.label_39.setGeometry(QtCore.QRect(570, 170, 131, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.channelregistersetting)
        self.label_40.setGeometry(QtCore.QRect(570, 30, 131, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.channelregistersetting)
        self.label_41.setGeometry(QtCore.QRect(570, 240, 131, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.channelregistersetting)
        self.label_42.setGeometry(QtCore.QRect(570, 100, 131, 16))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.frameCh1 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh1.setGeometry(QtCore.QRect(20, 50, 511, 51))
        self.frameCh1.setFrameShape(QtGui.QFrame.Box)
        self.frameCh1.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh1.setObjectName(_fromUtf8("frameCh1"))
        self.PDCh1 = QtGui.QComboBox(self.frameCh1)
        self.PDCh1.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh1.setObjectName(_fromUtf8("PDCh1"))
        self.GainCh1 = QtGui.QComboBox(self.frameCh1)
        self.GainCh1.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh1.setEditable(False)
        self.GainCh1.setObjectName(_fromUtf8("GainCh1"))
        self.SRB2Ch1 = QtGui.QComboBox(self.frameCh1)
        self.SRB2Ch1.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch1.setObjectName(_fromUtf8("SRB2Ch1"))
        self.ChanInCh1 = QtGui.QComboBox(self.frameCh1)
        self.ChanInCh1.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh1.setObjectName(_fromUtf8("ChanInCh1"))
        self.label_4 = QtGui.QLabel(self.frameCh1)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frameCh1)
        self.label_5.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frameCh1)
        self.label_6.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frameCh1)
        self.label_7.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.frameCh3 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh3.setGeometry(QtCore.QRect(20, 190, 511, 51))
        self.frameCh3.setFrameShape(QtGui.QFrame.Box)
        self.frameCh3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh3.setObjectName(_fromUtf8("frameCh3"))
        self.PDCh3 = QtGui.QComboBox(self.frameCh3)
        self.PDCh3.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh3.setObjectName(_fromUtf8("PDCh3"))
        self.GainCh3 = QtGui.QComboBox(self.frameCh3)
        self.GainCh3.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh3.setObjectName(_fromUtf8("GainCh3"))
        self.SRB2Ch3 = QtGui.QComboBox(self.frameCh3)
        self.SRB2Ch3.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch3.setObjectName(_fromUtf8("SRB2Ch3"))
        self.ChanInCh3 = QtGui.QComboBox(self.frameCh3)
        self.ChanInCh3.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh3.setObjectName(_fromUtf8("ChanInCh3"))
        self.label_13 = QtGui.QLabel(self.frameCh3)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frameCh3)
        self.label_14.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.frameCh3)
        self.label_15.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.frameCh3)
        self.label_16.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.frameCh4 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh4.setGeometry(QtCore.QRect(20, 260, 511, 51))
        self.frameCh4.setFrameShape(QtGui.QFrame.Box)
        self.frameCh4.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh4.setObjectName(_fromUtf8("frameCh4"))
        self.PDCh4 = QtGui.QComboBox(self.frameCh4)
        self.PDCh4.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh4.setObjectName(_fromUtf8("PDCh4"))
        self.GainCh4 = QtGui.QComboBox(self.frameCh4)
        self.GainCh4.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh4.setObjectName(_fromUtf8("GainCh4"))
        self.SRB2Ch4 = QtGui.QComboBox(self.frameCh4)
        self.SRB2Ch4.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch4.setObjectName(_fromUtf8("SRB2Ch4"))
        self.ChanInCh4 = QtGui.QComboBox(self.frameCh4)
        self.ChanInCh4.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh4.setObjectName(_fromUtf8("ChanInCh4"))
        self.label_18 = QtGui.QLabel(self.frameCh4)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.frameCh4)
        self.label_19.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.frameCh4)
        self.label_20.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frameCh4)
        self.label_21.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.frameCh2 = QtGui.QFrame(self.channelregistersetting)
        self.frameCh2.setGeometry(QtCore.QRect(20, 120, 511, 51))
        self.frameCh2.setFrameShape(QtGui.QFrame.Box)
        self.frameCh2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh2.setObjectName(_fromUtf8("frameCh2"))
        self.PDCh2 = QtGui.QComboBox(self.frameCh2)
        self.PDCh2.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.PDCh2.setObjectName(_fromUtf8("PDCh2"))
        self.GainCh2 = QtGui.QComboBox(self.frameCh2)
        self.GainCh2.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.GainCh2.setObjectName(_fromUtf8("GainCh2"))
        self.SRB2Ch2 = QtGui.QComboBox(self.frameCh2)
        self.SRB2Ch2.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch2.setObjectName(_fromUtf8("SRB2Ch2"))
        self.ChanInCh2 = QtGui.QComboBox(self.frameCh2)
        self.ChanInCh2.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh2.setObjectName(_fromUtf8("ChanInCh2"))
        self.label_8 = QtGui.QLabel(self.frameCh2)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frameCh2)
        self.label_9.setGeometry(QtCore.QRect(150, 0, 51, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frameCh2)
        self.label_10.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frameCh2)
        self.label_11.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_22 = QtGui.QLabel(self.channelregistersetting)
        self.label_22.setGeometry(QtCore.QRect(20, 240, 131, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_12 = QtGui.QLabel(self.channelregistersetting)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 131, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_17 = QtGui.QLabel(self.channelregistersetting)
        self.label_17.setGeometry(QtCore.QRect(20, 170, 131, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_3 = QtGui.QLabel(self.channelregistersetting)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tabWidget.addTab(self.channelregistersetting, _fromUtf8(""))
        self.globalregisterset = QtGui.QWidget()
        self.globalregisterset.setObjectName(_fromUtf8("globalregisterset"))
        self.SetCONFIG1 = QtGui.QGroupBox(self.globalregisterset)
        self.SetCONFIG1.setGeometry(QtCore.QRect(30, 30, 801, 80))
        self.SetCONFIG1.setObjectName(_fromUtf8("SetCONFIG1"))
        self.DaisyChainMultiRM = QtGui.QComboBox(self.SetCONFIG1)
        self.DaisyChainMultiRM.setGeometry(QtCore.QRect(20, 40, 191, 22))
        self.DaisyChainMultiRM.setObjectName(_fromUtf8("DaisyChainMultiRM"))
        self.ClkOut = QtGui.QComboBox(self.SetCONFIG1)
        self.ClkOut.setGeometry(QtCore.QRect(310, 40, 171, 22))
        self.ClkOut.setObjectName(_fromUtf8("ClkOut"))
        self.OutputDRate = QtGui.QComboBox(self.SetCONFIG1)
        self.OutputDRate.setGeometry(QtCore.QRect(550, 40, 191, 22))
        self.OutputDRate.setObjectName(_fromUtf8("OutputDRate"))
        self.label_43 = QtGui.QLabel(self.SetCONFIG1)
        self.label_43.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.SetCONFIG1)
        self.label_44.setGeometry(QtCore.QRect(310, 20, 161, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.SetCONFIG1)
        self.label_45.setGeometry(QtCore.QRect(550, 20, 181, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.tabWidget.addTab(self.globalregisterset, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.registerstatus = QtGui.QTextEdit(self.tab)
        self.registerstatus.setGeometry(QtCore.QRect(40, 40, 211, 41))
        self.registerstatus.setReadOnly(True)
        self.registerstatus.setObjectName(_fromUtf8("registerstatus"))
        self.Test = QtGui.QPushButton(self.tab)
        self.Test.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.Test.setObjectName(_fromUtf8("Test"))
        self.setSRDATA = QtGui.QPushButton(self.tab)
        self.setSRDATA.setGeometry(QtCore.QRect(310, 10, 75, 23))
        self.setSRDATA.setObjectName(_fromUtf8("setSRDATA"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.analysis = QtGui.QWidget()
        self.analysis.setObjectName(_fromUtf8("analysis"))
        self.tabWidget.addTab(self.analysis, _fromUtf8(""))
        self.save = QtGui.QWidget()
        self.save.setObjectName(_fromUtf8("save"))
        self.tabWidget.addTab(self.save, _fromUtf8(""))
        self.acquiredata = QtGui.QPushButton(self.centralwidget)
        self.acquiredata.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.acquiredata.setObjectName(_fromUtf8("acquiredata"))
        self.continuousdata = QtGui.QPushButton(self.centralwidget)
        self.continuousdata.setGeometry(QtCore.QRect(20, 220, 75, 23))
        self.continuousdata.setObjectName(_fromUtf8("continuousdata"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 430, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 490, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1259, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.GainCh1.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "EEG", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Dat Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Samples/CH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("mainWindow", "Channel 7 (CH7SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("mainWindow", "Channel 5 (CH5SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("mainWindow", "Channel 8 (CH8SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("mainWindow", "Channel 6 (CH6SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mainWindow", "Power-down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mainWindow", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("mainWindow", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("mainWindow", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("mainWindow", "Channel 4 (CH4SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("mainWindow", "Channel 2 (CH2SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("mainWindow", "Channel 3 (CH3SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Channel 1 (CH1SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.channelregistersetting), QtGui.QApplication.translate("mainWindow", "Channel Register Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.SetCONFIG1.setTitle(QtGui.QApplication.translate("mainWindow", "Set Register 1 (CONFIG1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("mainWindow", "Daisy-chain/Multiple Readback Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("mainWindow", "CLKOUT Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("mainWindow", "Output Data Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.globalregisterset), QtGui.QApplication.translate("mainWindow", "Global Register Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.Test.setText(QtGui.QApplication.translate("mainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.setSRDATA.setText(QtGui.QApplication.translate("mainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("mainWindow", "Register Map", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysis), QtGui.QApplication.translate("mainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.save), QtGui.QApplication.translate("mainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.acquiredata.setText(QtGui.QApplication.translate("mainWindow", "Acquire", None, QtGui.QApplication.UnicodeUTF8))
        self.continuousdata.setText(QtGui.QApplication.translate("mainWindow", "Continuous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("mainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("mainWindow", "Standby", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))

