# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Wed Apr 17 13:03:02 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1532, 660)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 20, 131, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.frameCh1 = QtGui.QFrame(Form)
        self.frameCh1.setGeometry(QtCore.QRect(90, 40, 521, 51))
        self.frameCh1.setFrameShape(QtGui.QFrame.Box)
        self.frameCh1.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCh1.setObjectName(_fromUtf8("frameCh1"))
        self.GainCh1 = QtGui.QComboBox(self.frameCh1)
        self.GainCh1.setGeometry(QtCore.QRect(130, 20, 81, 22))
        self.GainCh1.setEditable(False)
        self.GainCh1.setObjectName(_fromUtf8("GainCh1"))
        self.SRB2Ch1 = QtGui.QComboBox(self.frameCh1)
        self.SRB2Ch1.setGeometry(QtCore.QRect(238, 20, 81, 22))
        self.SRB2Ch1.setObjectName(_fromUtf8("SRB2Ch1"))
        self.ChanInCh1 = QtGui.QComboBox(self.frameCh1)
        self.ChanInCh1.setGeometry(QtCore.QRect(340, 20, 161, 22))
        self.ChanInCh1.setObjectName(_fromUtf8("ChanInCh1"))
        self.label_4 = QtGui.QLabel(self.frameCh1)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frameCh1)
        self.label_5.setGeometry(QtCore.QRect(140, 0, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frameCh1)
        self.label_6.setGeometry(QtCore.QRect(250, 0, 41, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frameCh1)
        self.label_7.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Ch1Select = QtGui.QCheckBox(self.frameCh1)
        self.Ch1Select.setGeometry(QtCore.QRect(50, 20, 70, 17))
        self.Ch1Select.setText(_fromUtf8(""))
        self.Ch1Select.setChecked(True)
        self.Ch1Select.setObjectName(_fromUtf8("Ch1Select"))
        self.SetCONFIG1 = QtGui.QGroupBox(Form)
        self.SetCONFIG1.setGeometry(QtCore.QRect(90, 20, 801, 80))
        self.SetCONFIG1.setObjectName(_fromUtf8("SetCONFIG1"))
        self.DaisyChainMultiRM = QtGui.QComboBox(self.SetCONFIG1)
        self.DaisyChainMultiRM.setGeometry(QtCore.QRect(20, 40, 191, 22))
        self.DaisyChainMultiRM.setObjectName(_fromUtf8("DaisyChainMultiRM"))
        self.ClkOut = QtGui.QComboBox(self.SetCONFIG1)
        self.ClkOut.setGeometry(QtCore.QRect(310, 40, 171, 22))
        self.ClkOut.setObjectName(_fromUtf8("ClkOut"))
        self.OutputDRate = QtGui.QComboBox(self.SetCONFIG1)
        self.OutputDRate.setGeometry(QtCore.QRect(550, 40, 191, 22))
        self.OutputDRate.setObjectName(_fromUtf8("OutputDRate"))
        self.label_43 = QtGui.QLabel(self.SetCONFIG1)
        self.label_43.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.SetCONFIG1)
        self.label_44.setGeometry(QtCore.QRect(310, 20, 161, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.SetCONFIG1)
        self.label_45.setGeometry(QtCore.QRect(550, 20, 181, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(680, 40, 131, 371))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.OutputDTRate = QtGui.QTextEdit(self.groupBox)
        self.OutputDTRate.setGeometry(QtCore.QRect(20, 50, 91, 31))
        self.OutputDTRate.setReadOnly(True)
        self.OutputDTRate.setObjectName(_fromUtf8("OutputDTRate"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.SamplePerChn = QtGui.QTextEdit(self.groupBox)
        self.SamplePerChn.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.SamplePerChn.setObjectName(_fromUtf8("SamplePerChn"))
        self.SetCONFIG2 = QtGui.QGroupBox(Form)
        self.SetCONFIG2.setGeometry(QtCore.QRect(90, 110, 801, 80))
        self.SetCONFIG2.setObjectName(_fromUtf8("SetCONFIG2"))
        self.TestSource = QtGui.QComboBox(self.SetCONFIG2)
        self.TestSource.setGeometry(QtCore.QRect(20, 40, 191, 22))
        self.TestSource.setObjectName(_fromUtf8("TestSource"))
        self.TestAmp = QtGui.QComboBox(self.SetCONFIG2)
        self.TestAmp.setGeometry(QtCore.QRect(310, 40, 171, 22))
        self.TestAmp.setObjectName(_fromUtf8("TestAmp"))
        self.TestFrq = QtGui.QComboBox(self.SetCONFIG2)
        self.TestFrq.setGeometry(QtCore.QRect(550, 40, 191, 22))
        self.TestFrq.setObjectName(_fromUtf8("TestFrq"))
        self.label_46 = QtGui.QLabel(self.SetCONFIG2)
        self.label_46.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.SetCONFIG2)
        self.label_47.setGeometry(QtCore.QRect(310, 20, 161, 16))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.SetCONFIG2)
        self.label_48.setGeometry(QtCore.QRect(550, 20, 181, 16))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.LOFFPNFLIP = QtGui.QGroupBox(Form)
        self.LOFFPNFLIP.setGeometry(QtCore.QRect(90, 280, 791, 191))
        self.LOFFPNFLIP.setObjectName(_fromUtf8("LOFFPNFLIP"))
        self.widget = QtGui.QWidget(self.LOFFPNFLIP)
        self.widget.setGeometry(QtCore.QRect(130, 40, 604, 19))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.LOFFP8 = QtGui.QCheckBox(self.widget)
        self.LOFFP8.setObjectName(_fromUtf8("LOFFP8"))
        self.horizontalLayout.addWidget(self.LOFFP8)
        self.LOFFP7 = QtGui.QCheckBox(self.widget)
        self.LOFFP7.setObjectName(_fromUtf8("LOFFP7"))
        self.horizontalLayout.addWidget(self.LOFFP7)
        self.LOFFP6 = QtGui.QCheckBox(self.widget)
        self.LOFFP6.setObjectName(_fromUtf8("LOFFP6"))
        self.horizontalLayout.addWidget(self.LOFFP6)
        self.LOFFP5 = QtGui.QCheckBox(self.widget)
        self.LOFFP5.setObjectName(_fromUtf8("LOFFP5"))
        self.horizontalLayout.addWidget(self.LOFFP5)
        self.LOFFP4 = QtGui.QCheckBox(self.widget)
        self.LOFFP4.setObjectName(_fromUtf8("LOFFP4"))
        self.horizontalLayout.addWidget(self.LOFFP4)
        self.LOFFP3 = QtGui.QCheckBox(self.widget)
        self.LOFFP3.setObjectName(_fromUtf8("LOFFP3"))
        self.horizontalLayout.addWidget(self.LOFFP3)
        self.LOFFP2 = QtGui.QCheckBox(self.widget)
        self.LOFFP2.setObjectName(_fromUtf8("LOFFP2"))
        self.horizontalLayout.addWidget(self.LOFFP2)
        self.LOFFP1 = QtGui.QCheckBox(self.widget)
        self.LOFFP1.setObjectName(_fromUtf8("LOFFP1"))
        self.horizontalLayout.addWidget(self.LOFFP1)
        self.widget1 = QtGui.QWidget(self.LOFFPNFLIP)
        self.widget1.setGeometry(QtCore.QRect(130, 90, 604, 19))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.LOFFN8 = QtGui.QCheckBox(self.widget1)
        self.LOFFN8.setObjectName(_fromUtf8("LOFFN8"))
        self.horizontalLayout_2.addWidget(self.LOFFN8)
        self.LOFFN7 = QtGui.QCheckBox(self.widget1)
        self.LOFFN7.setObjectName(_fromUtf8("LOFFN7"))
        self.horizontalLayout_2.addWidget(self.LOFFN7)
        self.LOFFN6 = QtGui.QCheckBox(self.widget1)
        self.LOFFN6.setObjectName(_fromUtf8("LOFFN6"))
        self.horizontalLayout_2.addWidget(self.LOFFN6)
        self.LOFFN5 = QtGui.QCheckBox(self.widget1)
        self.LOFFN5.setObjectName(_fromUtf8("LOFFN5"))
        self.horizontalLayout_2.addWidget(self.LOFFN5)
        self.LOFFN4 = QtGui.QCheckBox(self.widget1)
        self.LOFFN4.setObjectName(_fromUtf8("LOFFN4"))
        self.horizontalLayout_2.addWidget(self.LOFFN4)
        self.LOFFN3 = QtGui.QCheckBox(self.widget1)
        self.LOFFN3.setObjectName(_fromUtf8("LOFFN3"))
        self.horizontalLayout_2.addWidget(self.LOFFN3)
        self.LOFFN2 = QtGui.QCheckBox(self.widget1)
        self.LOFFN2.setObjectName(_fromUtf8("LOFFN2"))
        self.horizontalLayout_2.addWidget(self.LOFFN2)
        self.LOFFN1 = QtGui.QCheckBox(self.widget1)
        self.LOFFN1.setObjectName(_fromUtf8("LOFFN1"))
        self.horizontalLayout_2.addWidget(self.LOFFN1)
        self.widget2 = QtGui.QWidget(self.LOFFPNFLIP)
        self.widget2.setGeometry(QtCore.QRect(130, 140, 604, 19))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.LOFF_FLIP8 = QtGui.QCheckBox(self.widget2)
        self.LOFF_FLIP8.setObjectName(_fromUtf8("LOFF_FLIP8"))
        self.horizontalLayout_3.addWidget(self.LOFF_FLIP8)
        self.LOFF_FLIP7 = QtGui.QCheckBox(self.widget2)
        self.LOFF_FLIP7.setObjectName(_fromUtf8("LOFF_FLIP7"))
        self.horizontalLayout_3.addWidget(self.LOFF_FLIP7)
        self.LOFF_FLIP6 = QtGui.QCheckBox(self.widget2)
        self.LOFF_FLIP6.setObjectName(_fromUtf8("LOFF_FLIP6"))
        self.horizontalLayout_3.addWidget(self.LOFF_FLIP6)
        self.LOFF_FLIP5 = QtGui.QCheckBox(self.widget2)
        self.LOFF_FLIP5.setObjectName(_fromUtf8("LOFF_FLIP5"))
        self.horizontalLayout_3.addWidget(self.LOFF_FLIP5)
        self.LOFF_FLIP4 = QtGui.QCheckBox(self.widget2)
        self.LOFF_FLIP4.setObjectName(_fromUtf8("LOFF_FLIP4"))
        self.horizontalLayout_3.addWidget(self.LOFF_FLIP4)
        self.LOFF_FLIP3 = QtGui.QCheckBox(self.widget2)
        self.LOFF_FLIP3.setObjectName(_fromUtf8("LOFF_FLIP3"))
        self.horizontalLayout_3.addWidget(self.LOFF_FLIP3)
        self.LOFF_FLIP2 = QtGui.QCheckBox(self.widget2)
        self.LOFF_FLIP2.setObjectName(_fromUtf8("LOFF_FLIP2"))
        self.horizontalLayout_3.addWidget(self.LOFF_FLIP2)
        self.LOFFP1_3 = QtGui.QCheckBox(self.widget2)
        self.LOFFP1_3.setObjectName(_fromUtf8("LOFFP1_3"))
        self.horizontalLayout_3.addWidget(self.LOFFP1_3)

        self.retranslateUi(Form)
        self.GainCh1.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Channel 1 (CH1SET)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Channel Select", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "PGA Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "SRB2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Channel Input", None, QtGui.QApplication.UnicodeUTF8))
        self.SetCONFIG1.setTitle(QtGui.QApplication.translate("Form", "Set Register 1 (CONFIG1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("Form", "Daisy-chain/Multiple Readback Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Form", "CLKOUT Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Form", "Output Data Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Data Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Samples/CH", None, QtGui.QApplication.UnicodeUTF8))
        self.SetCONFIG2.setTitle(QtGui.QApplication.translate("Form", "Set Register 2 (CONFIG2)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("Form", "Test Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Form", "Test Signal Amplitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Form", "Test Signal Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFPNFLIP.setTitle(QtGui.QApplication.translate("Form", "Lead-off Detection and Current Direction Control Registers", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP8.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP7.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP6.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP5.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP4.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP3.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP2.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP1.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN8.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN7.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN6.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN5.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN4.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN3.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN2.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFN1.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFF_FLIP8.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFF_FLIP7.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFF_FLIP6.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFF_FLIP5.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFF_FLIP4.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFF_FLIP3.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFF_FLIP2.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.LOFFP1_3.setText(QtGui.QApplication.translate("Form", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))

