# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Thu Jun 27 15:36:05 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1532, 660)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(110, 310, 569, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 551, 111))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_5 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_3.addWidget(self.checkBox_5, 2, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout_3.addWidget(self.checkBox_10, 2, 2, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout_3.addWidget(self.checkBox_9, 1, 2, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout_3.addWidget(self.checkBox_8, 2, 1, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_3.addWidget(self.checkBox_7, 1, 1, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout_3.addWidget(self.checkBox_6, 1, 0, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout_3.addWidget(self.checkBox_11, 1, 3, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout_3.addWidget(self.checkBox_12, 2, 3, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout_3.addWidget(self.checkBox_13, 1, 4, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout_3.addWidget(self.checkBox_14, 2, 4, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.gridLayout_3.addWidget(self.checkBox_15, 1, 5, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout_3.addWidget(self.checkBox_16, 2, 5, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridLayout_3.addWidget(self.checkBox_17, 0, 2, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout_3.addWidget(self.checkBox_18, 0, 3, 1, 1)
        self.checkBox_19 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.gridLayout_3.addWidget(self.checkBox_19, 0, 4, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout_3.addWidget(self.checkBox_20, 0, 5, 1, 1)
        self.groupBox_1 = QtGui.QGroupBox(Form)
        self.groupBox_1.setGeometry(QtCore.QRect(110, 130, 569, 161))
        self.groupBox_1.setObjectName(_fromUtf8("groupBox_1"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 25, 551, 121))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_2 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.checkBox_4 = QtGui.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(0, 0, 149, 17))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_2.addWidget(self.frame_2, 4, 1, 1, 1)
        self.frame = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2.addWidget(self.frame, 6, 0, 1, 3)
        self.comboBox_fH_2 = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_fH_2.setObjectName(_fromUtf8("comboBox_fH_2"))
        self.gridLayout_2.addWidget(self.comboBox_fH_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_fL_2 = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_fL_2.setObjectName(_fromUtf8("comboBox_fL_2"))
        self.gridLayout_2.addWidget(self.comboBox_fL_2, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 4, 2, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.gridLayout_2.addWidget(self.comboBox_5, 1, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.checkBox_21 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_21.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_21.setText(_fromUtf8(""))
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.horizontalLayout.addWidget(self.checkBox_21)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(110, 480, 569, 101))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 551, 85))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout_4.setHorizontalSpacing(30)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox.setEnabled(False)
        self.doubleSpinBox.setReadOnly(True)
        self.doubleSpinBox.setAccelerated(False)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMaximum(1225.0)
        self.doubleSpinBox.setSingleStep(4.785)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.verticalLayout.addWidget(self.doubleSpinBox)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_4.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout_4.addWidget(self.comboBox_4, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(16)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_4.addWidget(self.spinBox, 2, 2, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_4.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.groupBox_0 = QtGui.QGroupBox(Form)
        self.groupBox_0.setGeometry(QtCore.QRect(110, 21, 569, 91))
        self.groupBox_0.setObjectName(_fromUtf8("groupBox_0"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_0)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 551, 61))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_fH = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_fH.setObjectName(_fromUtf8("comboBox_fH"))
        self.gridLayout.addWidget(self.comboBox_fH, 1, 0, 1, 1)
        self.comboBox_fL = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_fL.setObjectName(_fromUtf8("comboBox_fL"))
        self.gridLayout.addWidget(self.comboBox_fL, 1, 1, 1, 1)
        self.pushButton_ResetAmp = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_ResetAmp.setObjectName(_fromUtf8("pushButton_ResetAmp"))
        self.gridLayout.addWidget(self.pushButton_ResetAmp, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Channel Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Form", "Channel 11", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "Select All Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("Form", "Channel 13", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("Form", "Channel 7", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("Form", "Channel 12", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("Form", "Channel 6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Form", "Channel 5", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("Form", "Channel 8", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("Form", "Channel 14", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("Form", "Channel 9", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("Form", "Channel 15", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("Form", "Channel 10", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setText(QtGui.QApplication.translate("Form", "Channel 16", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setText(QtGui.QApplication.translate("Form", "Channel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setText(QtGui.QApplication.translate("Form", "Channel 2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setText(QtGui.QApplication.translate("Form", "Channel 3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setText(QtGui.QApplication.translate("Form", "Channel 4", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_1.setTitle(QtGui.QApplication.translate("Form", "ADC Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Form", "Two\'s Complement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Input Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "ADC Sample Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Output Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Form", "Absolute Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Electrode Inpedance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "DAC Capacitor Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Impedance Check Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Positive/Negative input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "DAC Output Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Form", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_0.setTitle(QtGui.QApplication.translate("Form", "Amplifier Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ResetAmp.setText(QtGui.QApplication.translate("Form", "Reset Amplifier", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Upper Bandwidth (fH)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Lower Bandwidth (fL)", None, QtGui.QApplication.UnicodeUTF8))

